version: "3.8"

services:
  yolo-detection:
    build: .
    container_name: yolo_detection_container
    volumes:
      - ./data:/app/data
      - ./output:/app/output
    environment:
      - ENV_FILE=.env
    ports:
      - "8100:8100"
